Update requirements.txt
pywin not a valid package for non-Windows installations causing error when trying to install.  Added conditional check for pip install.  

ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306